name: global (perform dev release)

on:
  push:
    branches:
      - main
    paths:
      - services/meet-bot/meeting-recorder/google-meets/**
      - services/ai-proxy/**
      - services/error-assistant/**
      - infrastructure/container-registry/**
      - .github/workflows/global-perform-dev-release.yml

env:
  AWS_REGION: ap-northeast-1
  AWS_ACCOUNT_ID: 322607082550
  GIT_EMAIL: devops@zunou.ai
  GIT_USER: Zunou Ops

jobs:
  deploy-meet-bot-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set env
        run: |
          echo "ECR_REPO=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/meet-bot-api" >> $GITHUB_ENV
          echo "CLUSTER=primary-development" >> $GITHUB_ENV
          echo "SERVICE=meet-bot-development" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t $ECR_REPO:development-latest services/meet-bot/meeting-recorder/google-meets
          docker push $ECR_REPO:development-latest

      - name: Trigger ECS deployment
        run: |
          aws ecs update-service \
            --cluster $CLUSTER \
            --service $SERVICE \
            --force-new-deployment

  deploy-ai-proxy-dev:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/ai-proxy

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Lambda
        run: make deploy-dev

  deploy-error-assistant-dev:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/error-assistant

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Lambda
        run: make deploy-dev