name: admin (test)

# Cancel in-progress jobs.
concurrency:
  group:              admin-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    # Only run tests on pull requests on stg
    branches-ignore:
      - 'main'
      - 'production' 
      - 'production-candidate-*' 
    paths:
      - .github/workflows/test-admin.yml
      - lib/zunou-graphql/**
      - lib/zunou-queries/**
      - lib/zunou-react/**
      - services/admin/**

jobs:
  check:
    runs-on: ubuntu-latest

    outputs:
      status: ${{ steps.changes.conclusion }}

    steps:
    - uses: actions/checkout@v4

    - uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          admin:
            - .github/workflows/test-admin.yml
            - lib/zunou-graphql/**
            - lib/zunou-queries/**
            - lib/zunou-react/**
            - services/admin/**

    - name: Check service changed
      if:  steps.changes.outputs.admin == 'true'
      run: echo "Service has changed - running CI" # exit_with_success

  admin:
    runs-on: ubuntu-latest

    needs: check
    if:    needs.check.outputs.status == 'success'

    defaults:
      run:
        working-directory: services/admin

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - uses: oven-sh/setup-bun@v1

    - name: Install packages
      run: yarn install

    - name: Lint
      run: make lint

    - name: Format
      run: make lint-fix && make prettier-fix && git checkout ../../yarn.lock && git diff --exit-code
